# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf-parser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='link',
        ),
        migrations.AddField(
            model_name='document',
            name='link',
            field=models.ManyToManyField(to='pdf-parser.Link'),
        ),
    ]
